server:
  port: 8082

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.3.33:30112/evo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: yV2jJxvNs8BD
      driverClassName: com.mysql.cj.jdbc.Driver
    other:
      jdbc-url: jdbc:sqlserver://192.168.3.104:1433;DatabaseName=oa
      username: ezoffice
      password: 13572468
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
