server:
  port: 5050

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true

# 配置日志信息
logging:
  config: classpath:templates/logback.xml
  file:
    path: ~/logs

# 配置Swagger相关信息
swagger:
  title: API接口文档
  description: z7-x Api Documentation
  version: 1.0.0
  contact:
    name: 谢中奇
    url: https://www.baidu.com
    email: https://mail.qq.com/


