server:
  port: 5050

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true

# 配置日志信息
logging:
  config: classpath:templates/logback.xml
  file:
    path: ~/logs

# 配置Swagger相关信息
swagger:
  title: SpringBoot + Spring Data JPA API
  description: Api Documentation
  version: v.1.0
  contact:
    name: z7-x
    url: https://www.baidu.com
    email: https://mail.qq.com/

# 自定义消息变量
SendMessage:
  WeChat: ${WECHAT_SEND}
  DingDing: ${DINGDING_SEND}




