spring:
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://127.0.0.1:3306/learning?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 1
